type: object
additionalProperties: false
description: Properties for API configuration

required:
  - port
  - db_url
  - tennant
  - meta_url
  - issuer_url
  - api_client_id
  - valid_origins

properties:
  tennant: { type: string }
  api_client_id: { type: string }
  port: { $ref: '#/definitions/port' }
  meta_url: { $ref: '#/definitions/url' }
  issuer_url: { $ref: '#/definitions/url' }
  db_url: { $ref: '#/definitions/auth_url' }
  valid_origins: { type: array, items: { type: string } }

definitions:
  port:
    type: integer
    minimum: 0
    maximum: 65535
  url:
    description: Properties for a URL configuration
    type: object
    required: [proto,host]
    additionalProperties: false
    properties:
      proto: { type: string }
      host: { type: string }
      port: { $ref: '#/definitions/port' }
      path: { type: string }
      query: { type: string }
  auth_url:
    description: Properties for a URL with basic auth
    type: object
    required: [url, user, pass]
    properties:
      url: { $ref: '#/definitions/url' }
      user: { type: string }
      pass: { type: string, secret: true }
